# Generated by Django 4.1.6 on 2023-02-04 05:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='images_imag_created_d57897_idx',
            old_name='images_imag_created_b41a97_idx',
        ),
    ]
