# Generated by Django 4.1.6 on 2023-02-05 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
